spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${IP:weekend-db.ctys01pcfdjr.ap-northeast-2.rds.amazonaws.com}:3306/innodb
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
security:
  jwt:
    token:
      security-key: secret-key
      expiration-length: 3600000

server:
  port: 8080